const menu = [
  {
    id: 1,
    title: "Sirens & Muses",
    genre: "fiction",
    rating: 3.96,
    img: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1635699132i/59336344.jpg",
    desc: `Sirens & Muses explores the intertwined lives of four art students at an elite university, delving into themes of creativity, ambition, and the complexities of personal relationships.`,
  },
  {
    id: 2,
    title: "these violent delights",
    genre: "fantasy",
    rating: 3.84,
    img: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1580958058i/50892212.jpg",
    desc: `These Violent Delights is a historical fantasy novel set in 1920s Shanghai, where a gang leader's daughter and her ex-lover must confront their past and a monstrous threat to save their city. `,
  },
  {
    id: 3,
    title: "the idiot",
    genre: "literary fiction",
    rating: 3.67,
    img: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1474782288i/30962053.jpg",
    desc: `The Idiot is a coming-of-age novel that follows Selin, a Harvard freshman in the 1990s, as she navigates the complexities of language, literature, and first love.`,
  },
  {
    id: 4,
    title: "Big Swiss",
    genre: "fiction",
    rating: 3.68,
    img: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1653958990i/60701439._SX300_.jpg",
    desc: `Big Swiss is a darkly comic novel about a transcriptionist for a sex therapist who becomes obsessed with a client known as "Big Swiss," leading to unexpected and transformative consequences in her own life. `,
  },
  {
    id: 5,
    title: "The poppy war",
    genre: "fantasy",
    rating: 4.17,
    img: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1515691735i/35068705.jpg",
    desc: `The Poppy War is a grimdark fantasy novel that follows Rin, a war orphan, who rises from poverty to attend an elite military academy, only to be drawn into a brutal and devastating war that forces her to confront her own destructive power.`,
  },
  {
    id: 6,
    title: "beautiful world, where are you",
    genre: "literary fiction",
    rating: 3.54,
    img: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1672783505i/75555793.jpg",
    desc: `Beautiful World, Where Are You is a contemporary novel that follows two best friends, Alice and Eileen, as they navigate complex relationships and the challenges of their late twenties while questioning the meaning of life and beauty in a changing world.`,
  },
  {
    id: 7,
    title: "we do what we do in the dark",
    genre: "fiction",
    rating: 3.55,
    img: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1628534108i/58735038._SX300_.jpg",
    desc: `We Do What We Do in the Dark is a novel about a young woman who becomes involved in a transformative and secretive affair with an older professor, exploring themes of love, loss, and identity.`,
  },
  {
    id: 8,
    title: "we hunt the flame",
    genre: "fantasy",
    rating: 3.89,
    img: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1551185822i/36492488.jpg",
    desc: `We Hunt the Flame is a young adult fantasy novel set in a magical Arabian-inspired world, following Zafira, a legendary hunter disguised as a man, and Nasir, the prince of death, as they embark on a quest to restore magic to their land.`,
  },
  {
    id: 9,
    title: "yerba buena",
    genre: "literary fiction",
    rating: 3.88,
    img: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1621454145i/57693648.jpg",
    desc: `Yerba Buena is a contemporary novel that follows the intertwined lives of two women, Sara and Emilie, as they navigate their personal struggles, careers, and a complex romantic relationship against the backdrop of a vibrant Los Angeles restaurant.`,
  },
];
export default menu;
